import 'package:vnote_client/models/mock/transaction_mock_model.dart';

class MockDataService {
  static var current = MockDataService();

  final List<TransactionMockModel> RECENT_TRANSACTIONS = [
    TransactionMockModel(
      transactionId: 'txn-001',
      userId: 'user-001',
      secondaryUserPhoneNumber: '+1 (555) 234-5678',
      amount: 150.00,
      note: 'Dinner split',
      transactionDirection: TransactionMockDirection.DEBIT,
      transactionType: TransactionMockType.TRANSFER,
      transactionStatus: TransactionMockStatus.COMPLETED,
      createdAt: DateTime(2026, 6, 27, 19, 30),
      updatedAt: DateTime(2026, 6, 27, 19, 31),
    ),
    TransactionMockModel(
      transactionId: 'txn-002',
      userId: 'user-001',
      secondaryUserPhoneNumber: '+1 (555) 876-5432',
      amount: 320.50,
      note: 'Rent contribution',
      transactionDirection: TransactionMockDirection.CREDIT,
      transactionType: TransactionMockType.TRANSFER,
      transactionStatus: TransactionMockStatus.COMPLETED,
      createdAt: DateTime(2026, 6, 26, 10, 15),
      updatedAt: DateTime(2026, 6, 26, 10, 16),
    ),
    TransactionMockModel(
      transactionId: 'txn-003',
      userId: 'user-001',
      secondaryUserPhoneNumber: '+1 (555) 345-6789',
      amount: 45.99,
      transactionDirection: TransactionMockDirection.DEBIT,
      transactionType: TransactionMockType.PAYMENT,
      transactionStatus: TransactionMockStatus.COMPLETED,
      createdAt: DateTime(2026, 6, 25, 14, 00),
      updatedAt: DateTime(2026, 6, 25, 14, 01),
    ),
    TransactionMockModel(
      transactionId: 'txn-004',
      userId: 'user-001',
      secondaryUserPhoneNumber: '+1 (555) 456-7890',
      amount: 200.00,
      note: 'Refund for cancelled order',
      transactionDirection: TransactionMockDirection.CREDIT,
      transactionType: TransactionMockType.REFUND,
      transactionStatus: TransactionMockStatus.COMPLETED,
      createdAt: DateTime(2026, 6, 24, 9, 45),
      updatedAt: DateTime(2026, 6, 24, 9, 50),
    ),
    TransactionMockModel(
      transactionId: 'txn-005',
      userId: 'user-001',
      secondaryUserPhoneNumber: '+1 (555) 567-8901',
      amount: 75.00,
      note: 'Grocery run',
      transactionDirection: TransactionMockDirection.DEBIT,
      transactionType: TransactionMockType.PAYMENT,
      transactionStatus: TransactionMockStatus.PENDING,
      createdAt: DateTime(2026, 6, 28, 8, 0),
      updatedAt: DateTime(2026, 6, 28, 8, 0),
    ),
    TransactionMockModel(
      transactionId: 'txn-006',
      userId: 'user-001',
      secondaryUserPhoneNumber: '+1 (555) 678-9012',
      amount: 500.00,
      note: 'Freelance payment',
      transactionDirection: TransactionMockDirection.CREDIT,
      transactionType: TransactionMockType.TRANSFER,
      transactionStatus: TransactionMockStatus.COMPLETED,
      createdAt: DateTime(2026, 6, 23, 16, 20),
      updatedAt: DateTime(2026, 6, 23, 16, 22),
    ),
    TransactionMockModel(
      transactionId: 'txn-007',
      userId: 'user-001',
      secondaryUserPhoneNumber: '+1 (555) 789-0123',
      amount: 12.50,
      transactionDirection: TransactionMockDirection.DEBIT,
      transactionType: TransactionMockType.PAYMENT,
      transactionStatus: TransactionMockStatus.FAILED,
      createdAt: DateTime(2026, 6, 22, 11, 5),
      updatedAt: DateTime(2026, 6, 22, 11, 5),
    ),
    TransactionMockModel(
      transactionId: 'txn-008',
      userId: 'user-001',
      secondaryUserPhoneNumber: '+1 (555) 890-1234',
      amount: 89.99,
      note: 'Concert tickets',
      transactionDirection: TransactionMockDirection.DEBIT,
      transactionType: TransactionMockType.TRANSFER,
      transactionStatus: TransactionMockStatus.CANCELLED,
      createdAt: DateTime(2026, 6, 21, 20, 0),
      updatedAt: DateTime(2026, 6, 21, 20, 30),
    ),
  ];
}
